nameOverride: "stg-demo"
fullnameOverride: "stg-demo"
app: "stg-demo"
image:
  repository: "quay.io/public"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: demo-linux-stg
  version: ""
